version: "3.8"

services:
  db:
    image: postgres:16-alpine
    restart: always
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./database/postgresql/sql/0001_bootstrap_db.sql:/docker-entrypoint-initdb.d/create_tables.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:4.4
    ports:
      - "27018:27017"

  redis:
    image: redis:7-alpine
    ports:
      - "16379:6379"

  mailpit:
    image: axllent/mailpit
    ports:
      - "18025:8025" # Web UI
      - "11025:1025" # SMTP Port
